// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sdkFFI)
import sdkFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sdk_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sdk_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol NotegramCoreProtocol : AnyObject {
    
    func createIdentity() throws  -> FfiPublicIdentity
    
    func decrypt(peer: FfiPeerAddress, message: Data, associatedData: Data) throws  -> Data
    
    func encrypt(peer: FfiPeerAddress, plaintext: Data, associatedData: Data) throws  -> Data
    
    func establishInboundSession(peer: FfiPeerAddress, signedPrekeyPriv: Data, oneTimePrekeyPriv: Data?, initiatorIdentityPub: Data, initiatorEphemeralPub: Data) throws 
    
    func establishOutboundSession(peer: FfiPeerAddress, bundle: FfiPreKeyBundle) throws  -> Data
    
    func hasSession(peer: FfiPeerAddress) throws  -> Bool
    
    func importIdentity(identityPriv: Data, signingSeed: Data, registrationId: UInt32) throws  -> FfiPublicIdentity
    
    func publicIdentity() throws  -> FfiPublicIdentity
    
}

open class NotegramCore:
    NotegramCoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_sdk_fn_clone_notegramcore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_sdk_fn_free_notegramcore(pointer, $0) }
    }

    
public static func `open`(masterKey: Data, dbPath: String)throws  -> NotegramCore {
    return try  FfiConverterTypeNotegramCore.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_constructor_notegramcore_open(
        FfiConverterData.lower(masterKey),
        FfiConverterString.lower(dbPath),$0
    )
})
}
    

    
open func createIdentity()throws  -> FfiPublicIdentity {
    return try  FfiConverterTypeFfiPublicIdentity.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_create_identity(self.uniffiClonePointer(),$0
    )
})
}
    
open func decrypt(peer: FfiPeerAddress, message: Data, associatedData: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_decrypt(self.uniffiClonePointer(),
        FfiConverterTypeFfiPeerAddress.lower(peer),
        FfiConverterData.lower(message),
        FfiConverterData.lower(associatedData),$0
    )
})
}
    
open func encrypt(peer: FfiPeerAddress, plaintext: Data, associatedData: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_encrypt(self.uniffiClonePointer(),
        FfiConverterTypeFfiPeerAddress.lower(peer),
        FfiConverterData.lower(plaintext),
        FfiConverterData.lower(associatedData),$0
    )
})
}
    
open func establishInboundSession(peer: FfiPeerAddress, signedPrekeyPriv: Data, oneTimePrekeyPriv: Data?, initiatorIdentityPub: Data, initiatorEphemeralPub: Data)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_establish_inbound_session(self.uniffiClonePointer(),
        FfiConverterTypeFfiPeerAddress.lower(peer),
        FfiConverterData.lower(signedPrekeyPriv),
        FfiConverterOptionData.lower(oneTimePrekeyPriv),
        FfiConverterData.lower(initiatorIdentityPub),
        FfiConverterData.lower(initiatorEphemeralPub),$0
    )
}
}
    
open func establishOutboundSession(peer: FfiPeerAddress, bundle: FfiPreKeyBundle)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_establish_outbound_session(self.uniffiClonePointer(),
        FfiConverterTypeFfiPeerAddress.lower(peer),
        FfiConverterTypeFfiPreKeyBundle.lower(bundle),$0
    )
})
}
    
open func hasSession(peer: FfiPeerAddress)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_has_session(self.uniffiClonePointer(),
        FfiConverterTypeFfiPeerAddress.lower(peer),$0
    )
})
}
    
open func importIdentity(identityPriv: Data, signingSeed: Data, registrationId: UInt32)throws  -> FfiPublicIdentity {
    return try  FfiConverterTypeFfiPublicIdentity.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_import_identity(self.uniffiClonePointer(),
        FfiConverterData.lower(identityPriv),
        FfiConverterData.lower(signingSeed),
        FfiConverterUInt32.lower(registrationId),$0
    )
})
}
    
open func publicIdentity()throws  -> FfiPublicIdentity {
    return try  FfiConverterTypeFfiPublicIdentity.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_sdk_fn_method_notegramcore_public_identity(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNotegramCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = NotegramCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> NotegramCore {
        return NotegramCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: NotegramCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NotegramCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: NotegramCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotegramCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> NotegramCore {
    return try FfiConverterTypeNotegramCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNotegramCore_lower(_ value: NotegramCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeNotegramCore.lower(value)
}


public struct FfiPeerAddress {
    public var userId: Int64
    public var deviceId: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(userId: Int64, deviceId: Int64) {
        self.userId = userId
        self.deviceId = deviceId
    }
}



extension FfiPeerAddress: Equatable, Hashable {
    public static func ==(lhs: FfiPeerAddress, rhs: FfiPeerAddress) -> Bool {
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userId)
        hasher.combine(deviceId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPeerAddress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPeerAddress {
        return
            try FfiPeerAddress(
                userId: FfiConverterInt64.read(from: &buf), 
                deviceId: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPeerAddress, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.userId, into: &buf)
        FfiConverterInt64.write(value.deviceId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPeerAddress_lift(_ buf: RustBuffer) throws -> FfiPeerAddress {
    return try FfiConverterTypeFfiPeerAddress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPeerAddress_lower(_ value: FfiPeerAddress) -> RustBuffer {
    return FfiConverterTypeFfiPeerAddress.lower(value)
}


public struct FfiPreKeyBundle {
    public var identityPub: Data
    public var signingPub: Data
    public var signedPrekeyPub: Data
    public var signedPrekeySig: Data
    public var oneTimePrekeyPub: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPub: Data, signingPub: Data, signedPrekeyPub: Data, signedPrekeySig: Data, oneTimePrekeyPub: Data?) {
        self.identityPub = identityPub
        self.signingPub = signingPub
        self.signedPrekeyPub = signedPrekeyPub
        self.signedPrekeySig = signedPrekeySig
        self.oneTimePrekeyPub = oneTimePrekeyPub
    }
}



extension FfiPreKeyBundle: Equatable, Hashable {
    public static func ==(lhs: FfiPreKeyBundle, rhs: FfiPreKeyBundle) -> Bool {
        if lhs.identityPub != rhs.identityPub {
            return false
        }
        if lhs.signingPub != rhs.signingPub {
            return false
        }
        if lhs.signedPrekeyPub != rhs.signedPrekeyPub {
            return false
        }
        if lhs.signedPrekeySig != rhs.signedPrekeySig {
            return false
        }
        if lhs.oneTimePrekeyPub != rhs.oneTimePrekeyPub {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identityPub)
        hasher.combine(signingPub)
        hasher.combine(signedPrekeyPub)
        hasher.combine(signedPrekeySig)
        hasher.combine(oneTimePrekeyPub)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPreKeyBundle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPreKeyBundle {
        return
            try FfiPreKeyBundle(
                identityPub: FfiConverterData.read(from: &buf), 
                signingPub: FfiConverterData.read(from: &buf), 
                signedPrekeyPub: FfiConverterData.read(from: &buf), 
                signedPrekeySig: FfiConverterData.read(from: &buf), 
                oneTimePrekeyPub: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPreKeyBundle, into buf: inout [UInt8]) {
        FfiConverterData.write(value.identityPub, into: &buf)
        FfiConverterData.write(value.signingPub, into: &buf)
        FfiConverterData.write(value.signedPrekeyPub, into: &buf)
        FfiConverterData.write(value.signedPrekeySig, into: &buf)
        FfiConverterOptionData.write(value.oneTimePrekeyPub, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPreKeyBundle_lift(_ buf: RustBuffer) throws -> FfiPreKeyBundle {
    return try FfiConverterTypeFfiPreKeyBundle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPreKeyBundle_lower(_ value: FfiPreKeyBundle) -> RustBuffer {
    return FfiConverterTypeFfiPreKeyBundle.lower(value)
}


public struct FfiPublicIdentity {
    public var identityPub: Data
    public var signingPub: Data
    public var registrationId: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityPub: Data, signingPub: Data, registrationId: UInt32) {
        self.identityPub = identityPub
        self.signingPub = signingPub
        self.registrationId = registrationId
    }
}



extension FfiPublicIdentity: Equatable, Hashable {
    public static func ==(lhs: FfiPublicIdentity, rhs: FfiPublicIdentity) -> Bool {
        if lhs.identityPub != rhs.identityPub {
            return false
        }
        if lhs.signingPub != rhs.signingPub {
            return false
        }
        if lhs.registrationId != rhs.registrationId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identityPub)
        hasher.combine(signingPub)
        hasher.combine(registrationId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPublicIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPublicIdentity {
        return
            try FfiPublicIdentity(
                identityPub: FfiConverterData.read(from: &buf), 
                signingPub: FfiConverterData.read(from: &buf), 
                registrationId: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPublicIdentity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.identityPub, into: &buf)
        FfiConverterData.write(value.signingPub, into: &buf)
        FfiConverterUInt32.write(value.registrationId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPublicIdentity_lift(_ buf: RustBuffer) throws -> FfiPublicIdentity {
    return try FfiConverterTypeFfiPublicIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPublicIdentity_lower(_ value: FfiPublicIdentity) -> RustBuffer {
    return FfiConverterTypeFfiPublicIdentity.lower(value)
}


public enum FfiError {

    
    
    case Store
    case Session
    case NoSession
    case BadPrekeySignature
    case BadKeyMaterial
    case NoIdentity
    case BadInput
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Store
        case 2: return .Session
        case 3: return .NoSession
        case 4: return .BadPrekeySignature
        case 5: return .BadKeyMaterial
        case 6: return .NoIdentity
        case 7: return .BadInput

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Store:
            writeInt(&buf, Int32(1))
        
        
        case .Session:
            writeInt(&buf, Int32(2))
        
        
        case .NoSession:
            writeInt(&buf, Int32(3))
        
        
        case .BadPrekeySignature:
            writeInt(&buf, Int32(4))
        
        
        case .BadKeyMaterial:
            writeInt(&buf, Int32(5))
        
        
        case .NoIdentity:
            writeInt(&buf, Int32(6))
        
        
        case .BadInput:
            writeInt(&buf, Int32(7))
        
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sdk_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_create_identity() != 64928) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_decrypt() != 60904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_encrypt() != 21142) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_establish_inbound_session() != 34263) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_establish_outbound_session() != 49654) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_has_session() != 34586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_import_identity() != 17143) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_method_notegramcore_public_identity() != 29040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sdk_checksum_constructor_notegramcore_open() != 19205) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all