// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_CLONE_NETSESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_CLONE_NETSESSION
void*_Nonnull uniffi_sdk_fn_clone_netsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_FREE_NETSESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_FREE_NETSESSION
void uniffi_sdk_fn_free_netsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NETSESSION_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NETSESSION_CONNECT
uint64_t uniffi_sdk_fn_constructor_netsession_connect(RustBuffer edge_addr, uint32_t route_dc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NETSESSION_RESUME
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NETSESSION_RESUME
uint64_t uniffi_sdk_fn_constructor_netsession_resume(RustBuffer edge_addr, uint32_t route_dc, RustBuffer auth_key, uint64_t auth_key_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_ACK_ENCRYPTED
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_ACK_ENCRYPTED
uint64_t uniffi_sdk_fn_method_netsession_ack_encrypted(void*_Nonnull ptr, RustBuffer server_msg_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_AUTHENTICATE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_AUTHENTICATE
uint64_t uniffi_sdk_fn_method_netsession_authenticate(void*_Nonnull ptr, RustBuffer verified, RustBuffer client_info, RustBuffer server_ed_pub
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_CLAIM_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_CLAIM_USERNAME
uint64_t uniffi_sdk_fn_method_netsession_claim_username(void*_Nonnull ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_DELIVERY_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_DELIVERY_STATUS
uint64_t uniffi_sdk_fn_method_netsession_delivery_status(void*_Nonnull ptr, RustBuffer client_msg_ids
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_DEVICES
uint64_t uniffi_sdk_fn_method_netsession_get_devices(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_ENCRYPTED_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_ENCRYPTED_MESSAGES
uint64_t uniffi_sdk_fn_method_netsession_get_encrypted_messages(void*_Nonnull ptr, int32_t limit
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_MY_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_MY_PROFILE
uint64_t uniffi_sdk_fn_method_netsession_get_my_profile(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_MY_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_MY_USERNAME
uint64_t uniffi_sdk_fn_method_netsession_get_my_username(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_PEER_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_PEER_BUNDLE
uint64_t uniffi_sdk_fn_method_netsession_get_peer_bundle(void*_Nonnull ptr, int64_t user_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_GET_PROFILE
uint64_t uniffi_sdk_fn_method_netsession_get_profile(void*_Nonnull ptr, int64_t user_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_KEYS_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_KEYS_STATUS
uint64_t uniffi_sdk_fn_method_netsession_keys_status(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_KEYS_UPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_KEYS_UPLOAD
uint64_t uniffi_sdk_fn_method_netsession_keys_upload(void*_Nonnull ptr, RustBuffer bundle
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_PENDING_UPDATE_KINDS
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_PENDING_UPDATE_KINDS
uint64_t uniffi_sdk_fn_method_netsession_pending_update_kinds(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_PING
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_PING
uint64_t uniffi_sdk_fn_method_netsession_ping(void*_Nonnull ptr, int64_t ping_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_RESOLVE_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_RESOLVE_USERNAME
uint64_t uniffi_sdk_fn_method_netsession_resolve_username(void*_Nonnull ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SEND_EMAIL_CODE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SEND_EMAIL_CODE
uint64_t uniffi_sdk_fn_method_netsession_send_email_code(void*_Nonnull ptr, RustBuffer email, RustBuffer purpose, int64_t device_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SEND_ENCRYPTED
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SEND_ENCRYPTED
uint64_t uniffi_sdk_fn_method_netsession_send_encrypted(void*_Nonnull ptr, RustBuffer client_msg_id, int64_t chat_id, RustBuffer schema, RustBuffer suite, RustBuffer recipients, RustBuffer associated_data, RustBuffer forward_info, RustBuffer reply_to
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SET_DEVICE_SIGNING_KEY
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SET_DEVICE_SIGNING_KEY
uint64_t uniffi_sdk_fn_method_netsession_set_device_signing_key(void*_Nonnull ptr, RustBuffer public_key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SET_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_SET_PROFILE
uint64_t uniffi_sdk_fn_method_netsession_set_profile(void*_Nonnull ptr, RustBuffer display_name, RustBuffer bio
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_TAKE_DELIVERY_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_TAKE_DELIVERY_UPDATES
uint64_t uniffi_sdk_fn_method_netsession_take_delivery_updates(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_TAKE_NEW_MESSAGE_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_TAKE_NEW_MESSAGE_UPDATES
uint64_t uniffi_sdk_fn_method_netsession_take_new_message_updates(void*_Nonnull ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_VERIFY_AND_AUTHENTICATE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_VERIFY_AND_AUTHENTICATE
uint64_t uniffi_sdk_fn_method_netsession_verify_and_authenticate(void*_Nonnull ptr, RustBuffer email, RustBuffer email_hash, RustBuffer code, RustBuffer client_info, RustBuffer server_ed_pub
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_VERIFY_EMAIL_CODE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NETSESSION_VERIFY_EMAIL_CODE
uint64_t uniffi_sdk_fn_method_netsession_verify_email_code(void*_Nonnull ptr, RustBuffer email, RustBuffer email_hash, RustBuffer code
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_CLONE_NOTEGRAMCORE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_CLONE_NOTEGRAMCORE
void*_Nonnull uniffi_sdk_fn_clone_notegramcore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_FREE_NOTEGRAMCORE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_FREE_NOTEGRAMCORE
void uniffi_sdk_fn_free_notegramcore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NOTEGRAMCORE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_CONSTRUCTOR_NOTEGRAMCORE_OPEN
void*_Nonnull uniffi_sdk_fn_constructor_notegramcore_open(RustBuffer master_key, RustBuffer db_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_CREATE_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_CREATE_IDENTITY
RustBuffer uniffi_sdk_fn_method_notegramcore_create_identity(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_DECRYPT
RustBuffer uniffi_sdk_fn_method_notegramcore_decrypt(void*_Nonnull ptr, RustBuffer peer, RustBuffer message, RustBuffer associated_data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_DECRYPT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_DECRYPT_MESSAGE
RustBuffer uniffi_sdk_fn_method_notegramcore_decrypt_message(void*_Nonnull ptr, RustBuffer peer, RustBuffer envelope_type, RustBuffer header, RustBuffer ciphertext, RustBuffer associated_data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ENCRYPT
RustBuffer uniffi_sdk_fn_method_notegramcore_encrypt(void*_Nonnull ptr, RustBuffer peer, RustBuffer plaintext, RustBuffer associated_data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ENCRYPT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ENCRYPT_MESSAGE
RustBuffer uniffi_sdk_fn_method_notegramcore_encrypt_message(void*_Nonnull ptr, int64_t sender_user_id, int64_t sender_device_id, RustBuffer peer, int64_t chat_id, RustBuffer client_msg_id, RustBuffer body, RustBuffer new_session_bundle, RustBuffer reply_to, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ESTABLISH_INBOUND_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ESTABLISH_INBOUND_SESSION
void uniffi_sdk_fn_method_notegramcore_establish_inbound_session(void*_Nonnull ptr, RustBuffer peer, RustBuffer signed_prekey_priv, RustBuffer one_time_prekey_priv, RustBuffer initiator_identity_pub, RustBuffer initiator_ephemeral_pub, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ESTABLISH_OUTBOUND_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ESTABLISH_OUTBOUND_SESSION
RustBuffer uniffi_sdk_fn_method_notegramcore_establish_outbound_session(void*_Nonnull ptr, RustBuffer peer, RustBuffer bundle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_GENERATE_PREKEY_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_GENERATE_PREKEY_BUNDLE
RustBuffer uniffi_sdk_fn_method_notegramcore_generate_prekey_bundle(void*_Nonnull ptr, uint32_t one_time_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_HAS_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_HAS_SESSION
int8_t uniffi_sdk_fn_method_notegramcore_has_session(void*_Nonnull ptr, RustBuffer peer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_IMPORT_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_IMPORT_IDENTITY
RustBuffer uniffi_sdk_fn_method_notegramcore_import_identity(void*_Nonnull ptr, RustBuffer identity_priv, RustBuffer signing_seed, uint32_t registration_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_LIST_CHAT_PREVIEWS
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_LIST_CHAT_PREVIEWS
RustBuffer uniffi_sdk_fn_method_notegramcore_list_chat_previews(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_LIST_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_LIST_MESSAGES
RustBuffer uniffi_sdk_fn_method_notegramcore_list_messages(void*_Nonnull ptr, int64_t chat_id, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MARK_MESSAGE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MARK_MESSAGE_STATUS
int8_t uniffi_sdk_fn_method_notegramcore_mark_message_status(void*_Nonnull ptr, int64_t chat_id, RustBuffer client_msg_id, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MARK_READ_UP_TO
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MARK_READ_UP_TO
uint32_t uniffi_sdk_fn_method_notegramcore_mark_read_up_to(void*_Nonnull ptr, int64_t chat_id, int64_t up_to_created_at, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MESSAGE_REF
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_MESSAGE_REF
int64_t uniffi_sdk_fn_method_notegramcore_message_ref(void*_Nonnull ptr, RustBuffer client_msg_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_PREKEY_TOP_UP
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_PREKEY_TOP_UP
RustBuffer uniffi_sdk_fn_method_notegramcore_prekey_top_up(void*_Nonnull ptr, uint32_t count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_PUBLIC_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_PUBLIC_IDENTITY
RustBuffer uniffi_sdk_fn_method_notegramcore_public_identity(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ROTATE_SIGNED_PREKEY
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_ROTATE_SIGNED_PREKEY
RustBuffer uniffi_sdk_fn_method_notegramcore_rotate_signed_prekey(void*_Nonnull ptr, uint32_t one_time_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_SAVE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_SAVE_MESSAGE
void uniffi_sdk_fn_method_notegramcore_save_message(void*_Nonnull ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_UNDELIVERED_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_UNDELIVERED_MESSAGES
RustBuffer uniffi_sdk_fn_method_notegramcore_undelivered_messages(void*_Nonnull ptr, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_VERIFY_PEER_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_FN_METHOD_NOTEGRAMCORE_VERIFY_PEER_BUNDLE
RustBuffer uniffi_sdk_fn_method_notegramcore_verify_peer_bundle(void*_Nonnull ptr, RustBuffer proof, RustBuffer trust, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_ALLOC
RustBuffer ffi_sdk_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_sdk_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_FREE
void ffi_sdk_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SDK_RUSTBUFFER_RESERVE
RustBuffer ffi_sdk_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U8
void ffi_sdk_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U8
void ffi_sdk_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U8
void ffi_sdk_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_sdk_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I8
void ffi_sdk_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I8
void ffi_sdk_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I8
void ffi_sdk_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I8
int8_t ffi_sdk_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U16
void ffi_sdk_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U16
void ffi_sdk_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U16
void ffi_sdk_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_sdk_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I16
void ffi_sdk_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I16
void ffi_sdk_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I16
void ffi_sdk_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I16
int16_t ffi_sdk_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U32
void ffi_sdk_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U32
void ffi_sdk_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U32
void ffi_sdk_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_sdk_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I32
void ffi_sdk_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I32
void ffi_sdk_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I32
void ffi_sdk_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I32
int32_t ffi_sdk_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_U64
void ffi_sdk_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_U64
void ffi_sdk_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_U64
void ffi_sdk_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_sdk_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_I64
void ffi_sdk_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_I64
void ffi_sdk_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_I64
void ffi_sdk_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_I64
int64_t ffi_sdk_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_F32
void ffi_sdk_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_F32
void ffi_sdk_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_F32
void ffi_sdk_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_F32
float ffi_sdk_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_F64
void ffi_sdk_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_F64
void ffi_sdk_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_F64
void ffi_sdk_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_F64
double ffi_sdk_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_POINTER
void ffi_sdk_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_POINTER
void ffi_sdk_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_POINTER
void ffi_sdk_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_sdk_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_sdk_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_sdk_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_sdk_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_sdk_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_POLL_VOID
void ffi_sdk_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_CANCEL_VOID
void ffi_sdk_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_FREE_VOID
void ffi_sdk_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SDK_RUST_FUTURE_COMPLETE_VOID
void ffi_sdk_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_ACK_ENCRYPTED
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_ACK_ENCRYPTED
uint16_t uniffi_sdk_checksum_method_netsession_ack_encrypted(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_AUTHENTICATE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_AUTHENTICATE
uint16_t uniffi_sdk_checksum_method_netsession_authenticate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_CLAIM_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_CLAIM_USERNAME
uint16_t uniffi_sdk_checksum_method_netsession_claim_username(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_DELIVERY_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_DELIVERY_STATUS
uint16_t uniffi_sdk_checksum_method_netsession_delivery_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_DEVICES
uint16_t uniffi_sdk_checksum_method_netsession_get_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_ENCRYPTED_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_ENCRYPTED_MESSAGES
uint16_t uniffi_sdk_checksum_method_netsession_get_encrypted_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_MY_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_MY_PROFILE
uint16_t uniffi_sdk_checksum_method_netsession_get_my_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_MY_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_MY_USERNAME
uint16_t uniffi_sdk_checksum_method_netsession_get_my_username(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_PEER_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_PEER_BUNDLE
uint16_t uniffi_sdk_checksum_method_netsession_get_peer_bundle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_GET_PROFILE
uint16_t uniffi_sdk_checksum_method_netsession_get_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_KEYS_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_KEYS_STATUS
uint16_t uniffi_sdk_checksum_method_netsession_keys_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_KEYS_UPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_KEYS_UPLOAD
uint16_t uniffi_sdk_checksum_method_netsession_keys_upload(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_PENDING_UPDATE_KINDS
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_PENDING_UPDATE_KINDS
uint16_t uniffi_sdk_checksum_method_netsession_pending_update_kinds(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_PING
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_PING
uint16_t uniffi_sdk_checksum_method_netsession_ping(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_RESOLVE_USERNAME
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_RESOLVE_USERNAME
uint16_t uniffi_sdk_checksum_method_netsession_resolve_username(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SEND_EMAIL_CODE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SEND_EMAIL_CODE
uint16_t uniffi_sdk_checksum_method_netsession_send_email_code(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SEND_ENCRYPTED
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SEND_ENCRYPTED
uint16_t uniffi_sdk_checksum_method_netsession_send_encrypted(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SET_DEVICE_SIGNING_KEY
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SET_DEVICE_SIGNING_KEY
uint16_t uniffi_sdk_checksum_method_netsession_set_device_signing_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SET_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_SET_PROFILE
uint16_t uniffi_sdk_checksum_method_netsession_set_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_TAKE_DELIVERY_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_TAKE_DELIVERY_UPDATES
uint16_t uniffi_sdk_checksum_method_netsession_take_delivery_updates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_TAKE_NEW_MESSAGE_UPDATES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_TAKE_NEW_MESSAGE_UPDATES
uint16_t uniffi_sdk_checksum_method_netsession_take_new_message_updates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_VERIFY_AND_AUTHENTICATE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_VERIFY_AND_AUTHENTICATE
uint16_t uniffi_sdk_checksum_method_netsession_verify_and_authenticate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_VERIFY_EMAIL_CODE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NETSESSION_VERIFY_EMAIL_CODE
uint16_t uniffi_sdk_checksum_method_netsession_verify_email_code(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_CREATE_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_CREATE_IDENTITY
uint16_t uniffi_sdk_checksum_method_notegramcore_create_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_DECRYPT
uint16_t uniffi_sdk_checksum_method_notegramcore_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_DECRYPT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_DECRYPT_MESSAGE
uint16_t uniffi_sdk_checksum_method_notegramcore_decrypt_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ENCRYPT
uint16_t uniffi_sdk_checksum_method_notegramcore_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ENCRYPT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ENCRYPT_MESSAGE
uint16_t uniffi_sdk_checksum_method_notegramcore_encrypt_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ESTABLISH_INBOUND_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ESTABLISH_INBOUND_SESSION
uint16_t uniffi_sdk_checksum_method_notegramcore_establish_inbound_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ESTABLISH_OUTBOUND_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ESTABLISH_OUTBOUND_SESSION
uint16_t uniffi_sdk_checksum_method_notegramcore_establish_outbound_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_GENERATE_PREKEY_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_GENERATE_PREKEY_BUNDLE
uint16_t uniffi_sdk_checksum_method_notegramcore_generate_prekey_bundle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_HAS_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_HAS_SESSION
uint16_t uniffi_sdk_checksum_method_notegramcore_has_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_IMPORT_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_IMPORT_IDENTITY
uint16_t uniffi_sdk_checksum_method_notegramcore_import_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_LIST_CHAT_PREVIEWS
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_LIST_CHAT_PREVIEWS
uint16_t uniffi_sdk_checksum_method_notegramcore_list_chat_previews(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_LIST_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_LIST_MESSAGES
uint16_t uniffi_sdk_checksum_method_notegramcore_list_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MARK_MESSAGE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MARK_MESSAGE_STATUS
uint16_t uniffi_sdk_checksum_method_notegramcore_mark_message_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MARK_READ_UP_TO
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MARK_READ_UP_TO
uint16_t uniffi_sdk_checksum_method_notegramcore_mark_read_up_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MESSAGE_REF
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_MESSAGE_REF
uint16_t uniffi_sdk_checksum_method_notegramcore_message_ref(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_PREKEY_TOP_UP
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_PREKEY_TOP_UP
uint16_t uniffi_sdk_checksum_method_notegramcore_prekey_top_up(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_PUBLIC_IDENTITY
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_PUBLIC_IDENTITY
uint16_t uniffi_sdk_checksum_method_notegramcore_public_identity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ROTATE_SIGNED_PREKEY
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_ROTATE_SIGNED_PREKEY
uint16_t uniffi_sdk_checksum_method_notegramcore_rotate_signed_prekey(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_SAVE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_SAVE_MESSAGE
uint16_t uniffi_sdk_checksum_method_notegramcore_save_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_UNDELIVERED_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_UNDELIVERED_MESSAGES
uint16_t uniffi_sdk_checksum_method_notegramcore_undelivered_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_VERIFY_PEER_BUNDLE
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_METHOD_NOTEGRAMCORE_VERIFY_PEER_BUNDLE
uint16_t uniffi_sdk_checksum_method_notegramcore_verify_peer_bundle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NETSESSION_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NETSESSION_CONNECT
uint16_t uniffi_sdk_checksum_constructor_netsession_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NETSESSION_RESUME
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NETSESSION_RESUME
uint16_t uniffi_sdk_checksum_constructor_netsession_resume(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NOTEGRAMCORE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_SDK_CHECKSUM_CONSTRUCTOR_NOTEGRAMCORE_OPEN
uint16_t uniffi_sdk_checksum_constructor_notegramcore_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SDK_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SDK_UNIFFI_CONTRACT_VERSION
uint32_t ffi_sdk_uniffi_contract_version(void
    
);
#endif

