use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine as _;
use kt::device::{verify_prekey_bundle_proof, TrustAnchors};
use serde_json::Value;

// Generated by `go run ./cmd/client-transparency-vectors` in session-gateway
// (store.BuildCanonicalClientTransparencyTestVectors). Regenerate after any
// change to the Go reference verifier or its vector generator.
const VECTORS_JSON: &str = include_str!("vectors/client_transparency_test_vectors.json");

fn load() -> Value {
    serde_json::from_str(VECTORS_JSON).expect("parse vectors json")
}

fn b64(v: &Value) -> Vec<u8> {
    BASE64.decode(v.as_str().expect("expected base64 string")).expect("valid base64")
}

fn trust_from(vectors: &Value) -> (Vec<[u8; 32]>, Vec<[u8; 32]>, usize) {
    let signing = vectors["trusted_signing_public_keys"]
        .as_array()
        .unwrap()
        .iter()
        .map(|k| b64(k).try_into().unwrap())
        .collect();
    let witness = vectors["trusted_witness_public_keys"]
        .as_array()
        .unwrap()
        .iter()
        .map(|k| b64(k).try_into().unwrap())
        .collect();
    let min = vectors["min_witness_signatures"].as_u64().unwrap() as usize;
    (signing, witness, min)
}

fn proof_bytes(vectors: &Value) -> Vec<u8> {
    b64(&vectors["prekey_bundle_proof"])
}

#[test]
fn verifies_canonical_go_vector_and_extracts_trusted_keys() {
    let vectors = load();
    let raw = proof_bytes(&vectors);
    let (signing, witness, min) = trust_from(&vectors);
    let trust = TrustAnchors {
        signing_public_keys: &signing,
        witness_public_keys: &witness,
        min_witness_signatures: min,
    };

    let verified = verify_prekey_bundle_proof(&raw, &trust).expect("verify canonical proof");

    assert_eq!(verified.user_id, vectors["subjects"]["peer_user_id"].as_i64().unwrap());
    assert_eq!(verified.device_id, vectors["subjects"]["peer_device_id"].as_i64().unwrap());
    assert_eq!(verified.device_signing_key.to_vec(), b64(&vectors["peer_device_signing_key"]));

    let inner: Value = serde_json::from_slice(&raw).unwrap();
    let receipt = &inner["receipt"];
    assert_eq!(verified.identity_key.to_vec(), b64(&receipt["IdentityKey"]));
    assert_eq!(verified.signed_pre_key_id, receipt["SignedPreKeyID"].as_i64().unwrap() as i32);
    assert_eq!(verified.signed_pre_key_pub.to_vec(), b64(&receipt["SignedPreKeyPub"]));
    assert_eq!(verified.signed_pre_key_sig.to_vec(), b64(&receipt["SignedPreKeySig"]));
    assert_eq!(verified.one_time_pre_key_id, receipt["OneTimePreKeyID"].as_i64().unwrap() as i32);
    assert_eq!(
        verified.one_time_pre_key_pub.expect("one-time prekey present").to_vec(),
        b64(&receipt["OneTimePreKeyPub"])
    );

    // Full chain: the DeviceSigningKey extracted from the KT log must
    // actually validate the signed-prekey signature via e2ee's X3DH check.
    // This is the whole point of C2-KT: establish_outbound can now trust it.
    assert!(e2ee::x3dh::verify_signed_prekey(
        &verified.device_signing_key,
        &verified.signed_pre_key_pub,
        &verified.signed_pre_key_sig,
    ));
}

#[test]
fn rejects_wrong_trusted_signing_key() {
    let vectors = load();
    let raw = proof_bytes(&vectors);
    let (_, witness, min) = trust_from(&vectors);
    let wrong_key = [0x42u8; 32];
    let trust = TrustAnchors {
        signing_public_keys: &[wrong_key],
        witness_public_keys: &witness,
        min_witness_signatures: min,
    };
    assert!(verify_prekey_bundle_proof(&raw, &trust).is_err());
}

#[test]
fn rejects_witness_threshold_not_met() {
    let vectors = load();
    let raw = proof_bytes(&vectors);
    let (signing, witness, _) = trust_from(&vectors);
    let trust = TrustAnchors {
        signing_public_keys: &signing,
        witness_public_keys: &witness,
        min_witness_signatures: 2, // canonical vector only carries 1 witness signature
    };
    assert!(verify_prekey_bundle_proof(&raw, &trust).is_err());
}

fn tamper_and_expect_err(vectors: &Value, mutate: impl FnOnce(&mut Value)) {
    let raw = proof_bytes(vectors);
    let mut inner: Value = serde_json::from_slice(&raw).unwrap();
    mutate(&mut inner);
    let mutated = serde_json::to_vec(&inner).unwrap();

    let (signing, witness, min) = trust_from(vectors);
    let trust = TrustAnchors {
        signing_public_keys: &signing,
        witness_public_keys: &witness,
        min_witness_signatures: min,
    };
    assert!(
        verify_prekey_bundle_proof(&mutated, &trust).is_err(),
        "mutated proof unexpectedly verified"
    );
}

fn flip_base64_byte(v: &mut Value, path: &[&str]) {
    let mut cur = v;
    for (i, key) in path.iter().enumerate() {
        cur = cur.get_mut(*key).unwrap_or_else(|| panic!("missing path segment {key}"));
        let _ = i;
    }
    let mut decoded = BASE64.decode(cur.as_str().unwrap()).unwrap();
    decoded[0] ^= 0xFF;
    *cur = Value::String(BASE64.encode(decoded));
}

#[test]
fn rejects_tampered_receipt_identity_key() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        flip_base64_byte(proof, &["receipt", "IdentityKey"]);
    });
}

#[test]
fn rejects_tampered_receipt_signature() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        flip_base64_byte(proof, &["receipt", "Signature"]);
    });
}

#[test]
fn rejects_tampered_checkpoint_root_hash() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        flip_base64_byte(proof, &["checkpoint", "RootHash"]);
    });
}

#[test]
fn rejects_tampered_checkpoint_signature() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        flip_base64_byte(proof, &["checkpoint", "Signature"]);
    });
}

#[test]
fn rejects_tampered_consistency_proof_root() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        flip_base64_byte(proof, &["consistency_proof", "ToRootHash"]);
    });
}

#[test]
fn rejects_tampered_device_signing_key_entry() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        let entries = proof["key_transparency_entries"].as_array_mut().unwrap();
        flip_base64_byte(&mut entries[0], &["DeviceSigningKey"]);
    });
}

#[test]
fn rejects_tampered_prekey_entry_signed_prekey_sig() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        let entries = proof["key_transparency_entries"].as_array_mut().unwrap();
        flip_base64_byte(&mut entries[1], &["SignedPreKeySig"]);
    });
}

#[test]
fn rejects_dropped_genesis_entry() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        let entries = proof["key_transparency_entries"].as_array_mut().unwrap();
        entries.remove(0);
    });
}

#[test]
fn rejects_tampered_witness_signature() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        let sigs = proof["witness_signatures"].as_array_mut().unwrap();
        flip_base64_byte(&mut sigs[0], &["Signature"]);
    });
}

#[test]
fn rejects_reordered_entries() {
    let vectors = load();
    tamper_and_expect_err(&vectors, |proof| {
        let entries = proof["key_transparency_entries"].as_array_mut().unwrap();
        entries.swap(0, 1);
    });
}
