package main

import (
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/notegram-io/commons/proto"
	"github.com/notegram-io/commons/tl"
)

func genMessages() {
	var b strings.Builder
	b.WriteString("# generated by core/parity (go run .); do not edit by hand\n")

	fwd := []byte{0xaa, 0xbb}
	reply := int64(-5)
	record := &proto.MessagesStoredRecord{
		ServerMsgID:        "m1",
		ClientMsgID:        "c1",
		SenderUserID:       7,
		SenderDeviceID:     1,
		RecipientUserID:    9,
		RecipientDeviceID:  2,
		ChatID:             100,
		Schema:             "s",
		Suite:              "x",
		EnvelopeType:       "msg",
		Header:             []byte("hdr"),
		Ciphertext:         []byte("ct"),
		AssociatedData:     []byte("ad"),
		ForwardInfo:        &fwd,
		ReplyTo:            &reply,
		MessageFingerprint: []byte("fp"),
		TransparencyProof:  []byte("proof"),
		CreatedAt:          1700000000000,
	}

	cases := []struct {
		name string
		obj  tl.Encodable
	}{
		{"Pong", &proto.Pong{PingID: 7, Now: 42}},
		{"MessagesPersisted", &proto.MessagesPersisted{ServerMsgID: "abc", CreatedAt: 1000, RecipientCount: 2}},
		{"MessagesPersistEncrypted", &proto.MessagesPersistEncrypted{Records: []*proto.MessagesStoredRecord{record}}},
	}

	for _, c := range cases {
		raw, err := proto.MarshalRawAppend(nil, c.obj)
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&b, "msg %s %s\n", c.name, hex.EncodeToString(raw))
	}

	out := filepath.Join("..", "crates", "tl", "tests", "messages.txt")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", out)
}
