package main

import (
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/notegram-io/commons/tl"
)

func genTL() {
	var b strings.Builder
	b.WriteString("# generated by core/parity (go run .); do not edit by hand\n")

	enc := func(f func(*tl.Encoder)) string {
		var e tl.Encoder
		f(&e)
		return hex.EncodeToString(e.Bytes())
	}

	for _, v := range []int32{0, 1, -1, 2147483647, -2147483648} {
		fmt.Fprintf(&b, "int %d %s\n", v, enc(func(e *tl.Encoder) { e.Int(v) }))
	}
	for _, v := range []int64{0, 1, -1, 9223372036854775807, -9223372036854775808} {
		fmt.Fprintf(&b, "long %d %s\n", v, enc(func(e *tl.Encoder) { e.Long(v) }))
	}
	for _, v := range []uint32{0, 1, 4294967295, 0xdeadbeef} {
		fmt.Fprintf(&b, "uint %d %s\n", v, enc(func(e *tl.Encoder) { e.UInt(v) }))
	}
	for _, v := range []uint64{0, 1, 18446744073709551615, 0x0102030405060708} {
		fmt.Fprintf(&b, "ulong %d %s\n", v, enc(func(e *tl.Encoder) { e.ULong(v) }))
	}
	for _, v := range []bool{true, false} {
		fmt.Fprintf(&b, "bool %t %s\n", v, enc(func(e *tl.Encoder) { e.Bool(v) }))
	}

	for _, n := range []int{0, 1, 2, 3, 4, 253, 254, 300} {
		payload := make([]byte, n)
		for i := range payload {
			payload[i] = byte(i)
		}
		fmt.Fprintf(&b, "bytes %s %s\n", hexOrDash(payload), enc(func(e *tl.Encoder) { _ = e.BytesTL(payload) }))
	}
	for _, s := range []string{"", "a", "alice", "пользователь", strings.Repeat("x", 300)} {
		fmt.Fprintf(&b, "string %s %s\n", hexOrDash([]byte(s)), enc(func(e *tl.Encoder) { _ = e.String(s) }))
	}

	for _, vals := range [][]int32{{}, {1, 2, 3}, {-1, 2147483647, 0}} {
		joined := "-"
		if len(vals) > 0 {
			parts := make([]string, len(vals))
			for i, v := range vals {
				parts[i] = strconv.FormatInt(int64(v), 10)
			}
			joined = strings.Join(parts, ",")
		}
		fmt.Fprintf(&b, "vector_int %s %s\n", joined, enc(func(e *tl.Encoder) {
			_ = e.Vector(len(vals), func(i int, e *tl.Encoder) error {
				e.Int(vals[i])
				return e.Err()
			})
		}))
	}

	out := filepath.Join("..", "crates", "tl", "tests", "vectors.txt")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", out)
}

func hexOrDash(b []byte) string {
	if len(b) == 0 {
		return "-"
	}
	return hex.EncodeToString(b)
}
