package main

import (
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/notegram-io/commons/wire"
)

func genWire() {
	var b strings.Builder
	b.WriteString("# generated by core/parity (go run .); do not edit by hand\n")

	for _, val := range []uint16{0, 1, 0x0102, 0xfffe, 0xffff} {
		fmt.Fprintf(&b, "int 16 %d %s\n", val, hex.EncodeToString(wire.AppendU16LE(nil, val)))
	}
	for _, val := range []uint32{0, 1, 0x0304_0506, 0x7fff_ffff, 0xffff_ffff} {
		fmt.Fprintf(&b, "int 32 %d %s\n", val, hex.EncodeToString(wire.AppendU32LE(nil, val)))
	}
	for _, val := range []uint64{0, 1, 0x0708_090a_0b0c_0d0e, 0xffff_ffff_ffff_ffff} {
		fmt.Fprintf(&b, "int 64 %d %s\n", val, hex.EncodeToString(wire.AppendU64LE(nil, val)))
	}

	for _, p := range [][]byte{nil, []byte("hello notegram"), make([]byte, 257)} {
		framed := append(wire.AppendU32LE(nil, uint32(len(p))), p...)
		ph := "-"
		if len(p) > 0 {
			ph = hex.EncodeToString(p)
		}
		fmt.Fprintf(&b, "frame %s %s\n", ph, hex.EncodeToString(framed))
	}

	out := filepath.Join("..", "crates", "wire", "tests", "vectors.txt")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", out)
}
